apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ref
resources:
  - ../base
patches:
  - path: replicas-patch.yaml
images:
  - name: frontend
    newName: ghcr.io/yourusername/frontend
    newTag: latest
